Update the script for pre-commit hook.

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -1,12 +1,15 @@
 #!/bin/sh
-
-echo "Running git pre-commit hook"
-# Run Detekt before each commit
-./gradlew detekt --console=plain
-# If Detekt fails, block commit
-if [ $? -ne 0 ]; then
-  echo "Detekt found issues. Please fix them before committing."
-  exit 1
-else
-  exit 0
+echo "Running detekt check..."
+OUTPUT="/tmp/detekt-$(date +%s)"
+./gradlew detekt > $OUTPUT
+EXIT_CODE=$?
+if [ $EXIT_CODE -ne 0 ]; then
+  cat $OUTPUT
+  rm $OUTPUT
+  echo "***********************************************"
+  echo "                 detekt failed                 "
+  echo " Please fix the above issues before committing "
+  echo "***********************************************"
+  exit $EXIT_CODE
 fi
+rm $OUTPUT
